Update e621dl.py
Wulfre/e621dl pull request #49
Opened 2022-11-02 20:31 UTC by RedFoxNightfox

added error catching to retry on 10054 and other network errors.

added logging to log file.

2022-11-03 23:08 UTC, Wulfre requested changes
Sorry for missing your original issue. I've been busy with other projects and didn't see the email for it.

I added some quick reviews to your request that are all semantic, the functionality looks fine. I can merge your pull and make the changes myself, but I wanted to see if you'd like to do them first so that you get full credit for the fix.

2022-11-03 23:08 UTC, Wulfre commented on e621dl.py
> +LOG_FILENAME = 'ErrorLog.txt'
Move to constants module.

2022-11-03 23:08 UTC, Wulfre commented on e621dl.py
> +CheckLogs = 'FALSE'
Use boolean instead of string, follow naming convention for variables.
`checkLogs = False`

2022-11-03 23:08 UTC, Wulfre commented on e621dl.py
> +                        CheckLogs = 'TRUE'
Use boolean instead of string, follow naming convention for variables.

2022-11-03 23:08 UTC, Wulfre commented on e621dl.py
> +                        CheckLogs = 'TRUE'
Use boolean instead of string, follow naming convention for variables.

2022-11-03 23:08 UTC, Wulfre commented on e621dl.py
> +    if CheckLogs == 'TRUE':
Use boolean instead of string, follow naming convention for variables.

2022-11-04 00:21 UTC, RedFoxNightfox commented
Made the changes requested.

2022-11-04 03:04 UTC, Wulfre commented
Thanks for that. I know this hasn't been updated in a long time, but it makes it easier to go back read in the future if everything is consistent.

2022-11-04 03:15 UTC, merged